# Generated by Django 6.0 on 2025-12-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(help_text="Введите цену", verbose_name="Цена"),
        ),
    ]
