# Generated by Django 6.0 on 2025-12-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Token"
            ),
        ),
    ]
