# Generated by Django 6.0 on 2025-12-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="token",
        ),
    ]
