# Generated by Django 6.0 on 2025-12-22 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_remove_product_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
    ]
