# Generated by Django 6.0 on 2025-12-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publication_status",
            field=models.BooleanField(default=False, verbose_name="Статус публикации"),
        ),
    ]
