# Generated by Django 6.0 on 2026-01-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_alter_product_options_alter_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                help_text="Введите категорию продукта",
                max_length=30,
                null=True,
                verbose_name="Категория",
            ),
        ),
    ]
