# Generated by Django 6.0 on 2025-12-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                height_field=150,
                help_text="Загрузите аватар",
                null=True,
                upload_to="media/user",
                verbose_name="Аватар",
                width_field=150,
            ),
        ),
    ]
