# Generated by Django 6.0 on 2025-12-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="publication_status",
            field=models.BooleanField(default=True),
        ),
    ]
