# Generated by Django 6.0 on 2025-12-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_user_publication_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="publication_status",
            field=models.BooleanField(default=False),
        ),
    ]
