# Generated by Django 6.0 on 2025-12-22 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_publication_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="publication_status",
        ),
    ]
