# Generated by Django 6.0 on 2025-12-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_remove_user_publication_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("product_removal", "Product removal"),
                    ("can_unpublish_product", "Can unpublish product"),
                ],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
