# Generated by Django 6.0 on 2025-12-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
