# Generated by Django 6.0 on 2025-12-22 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
